name: Testes Agibank

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run ServeRest
        run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest:latest

      - name: Cypress run
        uses: cypress-io/github-action@v2
